# project and group list
PROJECTS_AND_GROUPS = [
    ('project-1', 'group-1@example.com'),
    ('project-2', 'group-2@example.com'),
    ('project-3', 'group-3@example.com'),
    ('project-4', 'group-4@example.com'),
    ('project-5', 'group-5@example.com'),
    ('project-6', 'group-6@example.com'),
    ('project-7', 'group-7@example.com'),
    ('project-8', 'group-8@example.com'),
    ('project-9', 'group-9@example.com'),
    ('project-10', 'group-10@example.com'),
    ('project-11', 'group-11@example.com'),
    ('project-12', 'group-12@example.com'),
    ('project-13', 'group-13@example.com'),
    ('project-14', 'group-14@example.com'),
    ('project-15', 'group-15@example.com'),
    ('project-16', 'group-16@example.com'),
    ('project-17', 'group-17@example.com'),
    ('project-18', 'group-18@example.com'),
    ('project-19', 'group-19@example.com'),
    ('project-20', 'group-20@example.com'),
    ('project-21', 'group-20@example.com'),
    ('project-22', 'group-20@example.com'),
    ('project-23', 'group-23@example.com'),
    ('project-24', 'group-24@example.com'),
    ('project-25', 'group-25@example.com'),
    ('project-26', 'group-26@example.com')
]